# -*- coding: utf-8 -*-
"""Predicting next word

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Yr6BV1ynQgaiQ0LdNKctNLxWWavkUYa
"""

import random

# define the input text
text = "the quick brown fox jumps over the lazy dog"

# convert the text into a list of words
words = text.split()

# create a dictionary to store the frequency of each word
freq = {}
for i in range(len(words)-1):
    if words[i] not in freq:
        freq[words[i]] = {}
    if words[i+1] not in freq[words[i]]:
        freq[words[i]][words[i+1]] = 0
    freq[words[i]][words[i+1]] += 1

# define a function to predict the next word
def predict_next_word(text):
    # convert the input text into a list of words
    words = text.split()

    # get the last word in the input text
    last_word = words[-1]

    # get the dictionary of frequencies for the last word
    freq_dict = freq.get(last_word, {})

    # if there are no frequencies for the last word, return a random word
    if not freq_dict:
        return random.choice(words)

    # otherwise, return the word with the highest frequency
    next_word = max(freq_dict, key=freq_dict.get)
    return next_word

# test the function
input_text = "the quick brown"
next_word = predict_next_word(input_text)
print(next_word)